CREATE OR REPLACE FUNCTION DEV_DB_VISEO.SAP_GOLD.DUEDATEFORCASHDISCOUNT2("IP_KOART" VARCHAR(16777216), "IP_ZFBDT" DATE, "IP_BLDAT" DATE, "IP_SHKZG" VARCHAR(16777216), "IP_REBZG" VARCHAR(16777216), "IP_ZBD3T" NUMBER(38,0), "IP_ZBD2T" NUMBER(38,0), "IP_ZBD1T" NUMBER(38,0))
RETURNS DATE
LANGUAGE SQL
AS '
  SELECT CASE
           WHEN Ip_ZBD2T IS NOT NULL THEN 
             DATEADD(DAY, CAST(COALESCE(Ip_ZBD2T, 0) AS INT), Ip_ZFBDT)
           ELSE
             SAP_GOLD.NetDueDateCalc(
               Ip_Koart, Ip_ZFBDT, Ip_BLDAT, Ip_Shkzg, Ip_REBZG, Ip_ZBD3T, Ip_ZBD2T, Ip_ZBD1T
             )
         END
'; 