CREATE OR REPLACE FUNCTION DEV_DB_VISEO.SAP_GOLD.FISCAL_CASE1("IP_MANDT" VARCHAR, "IP_PERIV" VARCHAR, "IP_DATE" DATE)
RETURNS VARCHAR
LANGUAGE SQL
AS '
  SELECT
    CONCAT(
      EXTRACT(YEAR  FROM ip_date),
      LPAD(TO_CHAR(EXTRACT(MONTH FROM ip_date)), 2, ''0'')
    )
';