CREATE OR REPLACE FUNCTION DEV_DB_VISEO.SAP_GOLD.NETDUEDATECALC("IP_KOART" VARCHAR(16777216), "IP_ZFBDT" DATE, "IP_BLDAT" DATE, "IP_SHKZG" VARCHAR(16777216), "IP_REBZG" VARCHAR(16777216), "IP_ZBD3T" NUMBER(38,0), "IP_ZBD2T" NUMBER(38,0), "IP_ZBD1T" NUMBER(38,0))
RETURNS DATE
LANGUAGE SQL
AS '
  SELECT DATEADD(
    ''DAY'',
    CAST(
      CASE
        WHEN ip_koart = ''D'' AND ip_shkzg = ''H'' AND ip_REBZG IS NULL THEN 0
        WHEN ip_koart = ''D'' AND ip_ZBD3T IS NOT NULL THEN ip_ZBD3T
        WHEN ip_koart = ''D'' AND ip_ZBD2T IS NOT NULL THEN ip_ZBD2T
        WHEN ip_koart = ''D'' AND ip_ZBD1T IS NOT NULL THEN ip_ZBD1T
        WHEN ip_ZBD1T IS NULL THEN 0
      END AS INTEGER
    ),
    CASE
      WHEN ip_koart = ''D'' AND ip_ZFBDT IS NULL THEN ip_BLDAT
      ELSE ip_ZFBDT
    END
  )
';