-- Create schemas for data marts
CREATE SCHEMA IF NOT EXISTS DEV_DB_VISEO.SALES_ORDERS;


-- Clone tables from SAP_GOLD to SALES_ORDERS data mart
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.COUNTRIESMD CLONE DEV_DB_VISEO.SAP_GOLD.COUNTRIESMD;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.CUSTOMERSMD CLONE DEV_DB_VISEO.SAP_GOLD.CUSTOMERSMD;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.MaterialsMD CLONE DEV_DB_VISEO.SAP_GOLD.MaterialsMD;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.ProductionOrders CLONE DEV_DB_VISEO.SAP_GOLD.ProductionOrders;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.SALESFULFILLMENT CLONE DEV_DB_VISEO.SAP_GOLD.SALESFULFILLMENT;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.SalesFulfillment_PerOrder CLONE DEV_DB_VISEO.SAP_GOLD.SalesFulfillment_PerOrder;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.SalesOrders CLONE DEV_DB_VISEO.SAP_GOLD.SalesOrders;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.SALESSTATUS_ITEMS CLONE DEV_DB_VISEO.SAP_GOLD.SALESSTATUS_ITEMS;
CREATE TABLE DEV_DB_VISEO.SALES_ORDERS.CALENDAR_DATE_DIM CLONE DEV_DB_VISEO.UTILS.CALENDAR_DATE_DIM;

