CREATE SCHEMA IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH;


-- Clone table IF NOT EXISTSs from SAP_GOLD to ORDER_TO_CASH data mart
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.BILLING CLONE DEV_DB_VISEO.SAP_GOLD.BILLING; -- DONE
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.CUSTOMERSMD CLONE DEV_DB_VISEO.SAP_GOLD.CUSTOMERSMD; -- DONE
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.MaterialsMD CLONE DEV_DB_VISEO.SAP_GOLD.MaterialsMD; -- DONE
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.Deliveries CLONE DEV_DB_VISEO.SAP_GOLD.Deliveries; -- DONE
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.DistributionChannelsMD CLONE DEV_DB_VISEO.SAP_GOLD.DistributionChannelsMD; -- DONE
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.OneTouchOrder CLONE DEV_DB_VISEO.SAP_GOLD.OneTouchOrder; -- DONE
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.OrderToCash CLONE DEV_DB_VISEO.SAP_GOLD.OrderToCash; -- DONE
CREATE TABLE IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH.SalesOrganizationsMD CLONE DEV_DB_VISEO.SAP_GOLD.SalesOrganizationsMD; -- DONE