CREATE SCHEMA IF NOT EXISTS DEV_DB_VISEO.ORDER_TO_CASH;


-- Clone tables from SAP_GOLD to ORDER_TO_CASH data mart
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.BILLING CLONE DEV_DB_VISEO.SAP_GOLD.BILLING; -- TO CREATE !!!
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.CUSTOMERSMD CLONE DEV_DB_VISEO.SAP_GOLD.CUSTOMERSMD; -- DONE
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.MaterialsMD CLONE DEV_DB_VISEO.SAP_GOLD.MaterialsMD; -- DONE
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.Deliveries CLONE DEV_DB_VISEO.SAP_GOLD.Deliveries; -- TO CREATE !!
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.DistributionChannelsMD CLONE DEV_DB_VISEO.SAP_GOLD.DistributionChannelsMD; -- TO CREATE !!
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.OneTocuhOrder CLONE DEV_DB_VISEO.SAP_GOLD.OneTouchOrder; -- TO CREATE !!
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.OrderToCash CLONE DEV_DB_VISEO.SAP_GOLD.OrderToCash; -- TO CREATE !!
CREATE TABLE DEV_DB_VISEO.ORDER_TO_CASH.SalesOrganizationsMD CLONE DEV_DB_VISEO.UTILS.SalesOrganizationsMD; -- TO CREATE !!!