-- Create schemas for data marts
CREATE SCHEMA IF NOT EXISTS DEV_DB_VISEO.VENDOR_PERFORMANCE;


-- Clone tables from SAP_GOLD to VENDOR_PERFORMANCE data mart
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.countries_flag CLONE DEV_DB_VISEO.SAP_GOLD.countries_flag; -- NOT FOUND !!!!
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.CurrenciesMD CLONE DEV_DB_VISEO.SAP_GOLD.CurrenciesMD; -- DONE
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.MaterialsMD CLONE DEV_DB_VISEO.SAP_GOLD.MaterialsMD; -- DONE
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.MaterialTypesMD CLONE DEV_DB_VISEO.SAP_GOLD.MaterialTypesMD; -- DONE
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.POVendorConfirmation CLONE DEV_DB_VISEO.SAP_GOLD.POVendorConfirmation; -- DONE !! 
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.PurchaseDocuments CLONE DEV_DB_VISEO.SAP_GOLD.PurchaseDocuments; -- DONE
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.PurchaseDocumentsHistory CLONE DEV_DB_VISEO.SAP_GOLD.PurchaseDocumentsHistory; -- DONE
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.PurchasingOrganizationsMD CLONE DEV_DB_VISEO.SAP_GOLD.PurchasingOrganizationsMD; -- DONE
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.VendorPerformance CLONE DEV_DB_VISEO.SAP_GOLD.VendorPerformance; -- NOT YET 
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.CALENDAR_DATE_DIM CLONE DEV_DB_VISEO.UTILS.CALENDAR_DATE_DIM; -- DONE
CREATE TABLE DEV_DB_VISEO.VENDOR_PERFORMANCE.VENDORSMD CLONE DEV_DB_VISEO.SAP_GOLD.VENDORSMD; -- DONE 

