name: CI/CD for dbt Project

on:
  push:
    branches:
      - main
    schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dbt
        run: pip install dbt

      - name: Install dbt-snowflake adapter
        run: pip install dbt-snowflake

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "
          default:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                database: $SNOWFLAKE_DATABASE
                warehouse: $SNOWFLAKE_WAREHOUSE
                schema: $SNOWFLAKE_SCHEMA
                threads: 4
          " > ~/.dbt/profiles.yml
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

      - name: Run dbt debug
        run: dbt debug

      - name: Run dbt deps
        run: dbt deps

      - name: Run dbt run
        run: dbt run

      - name: Run dbt test
        run: dbt test
