name: Workflow To Deploy Gold UDF's

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_gold_udfs.yml'
      - 'dev_poc_sap/POC_SAP_SILVER/User_Defined_Functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch two commits to ensure HEAD~1 is available

      - name: Install SnowSQL
        run: |
          mkdir -p ~/bin
          curl -O "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.28-linux_x86_64.bash"
          export SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile
          bash snowsql-1.2.28-linux_x86_64.bash
          echo "${HOME}/bin" >> $GITHUB_PATH
          chmod +x ~/bin/snowsql
          
      - name: Deploy all UDF SQL files to Snowflake
        run: |
          sql_files=$(find dev_poc_sap/POC_SAP_SILVER/User_Defined_Functions -name '*.sql')
          if [ -z "$sql_files" ]; then
            echo "No SQL files found."
            exit 0
          fi
          for sql_file in $sql_files; do
            echo "Processing $sql_file"
            echo "Executing $sql_file"
            snowsql -f "$sql_file" -o friendly=false -o log_level=DEBUG
          done