name: Workflow to Deploy SAP_BRONZE Schema Objects

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_sap_bronze.yml'
      - 'dev_poc_sap/POC_SAP_BRONZE/**'
  workflow_dispatch:

jobs:
  deploy_sap_bronze:    # Updated job name to match its purpose
    runs-on: ubuntu-22.04    # Updated to newer Ubuntu version

    env:
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          mkdir -p ~/bin
          curl -O "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.28-linux_x86_64.bash"
          export SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile
          bash snowsql-1.2.28-linux_x86_64.bash
          echo "${HOME}/bin" >> $GITHUB_PATH
          chmod +x ~/bin/snowsql

      - name: Deploy Stored Procedure To Create Silver Structure
        run: |
          snowsql -f dev_poc_sap/POC_SAP_BRONZE/DEV_CREATE_SILVER_SP.sql -o friendly=false -o log_level=DEBUG

      - name: Deploy Stored Procedure for the Automated MERGE
        run: |
          snowsql -f dev_poc_sap/POC_SAP_BRONZE/DEV_SAP_MERGE_SP.sql -o friendly=false -o log_level=DEBUG

      - name: Deploy Stored Procedure for the BRONZE TO SILVER Transformation
        run: |
          snowsql -f dev_poc_sap/POC_SAP_BRONZE/DEV_TRANSFORM_BRONZE_TO_SILVER_SP.sql -o friendly=false -o log_level=DEBUG

      - name: Deploy Task for Bronze To Silver Orchestrated
        run: |
          snowsql -f dev_poc_sap/POC_SAP_BRONZE/DEV_BRONZE_TO_SILVER_TASK.sql -o friendly=false -o log_level=DEBUG