name: Workflow to Setup Snowflake Environment

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/setup_snowflake_env.yml'
  workflow_dispatch:

jobs:
  setup_snowflake:
    runs-on: ubuntu-20.04  # Using Ubuntu 20.04 for better compatibility

    env:
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          mkdir -p ~/bin
          curl -O "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.28-linux_x86_64.bash"
          bash snowsql-1.2.28-linux_x86_64.bash -f
          echo "${HOME}/bin" >> $GITHUB_PATH

      - name: Execute Snowflake Setup Script
        run: |
          echo "Executing Snowflake Setup Script"
          snowsql -f poc_setup/DEV_SNOWFLAKE_SETUP.SQL -o friendly=false -o log_level=DEBUG