name: know the directory hh

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: know the dir
        run: pwd
      - name: list the subdir
        run: ls -a